### ISSUE TITLE
Have Docker container access application not bound to 0.0.0.0

### ISSUE THREAD

**Issue by Mastergalen** [qoomon/docker-host#12]
I'm trying to set up a reverse nginx proxy so that I can password protect a Tensorboard instance running on the host on port `7005`.

If I run Tensorboard with `--host=127.0.0.1`, the Docker container gets a connection refused error when trying to access `http://docker-host:7005`. 

The Docker container is, however, able to access `http://docker-host:7005` with  Tensorboard launched with`--host=0.0.0.0`, but then I have Tensorboard exposed without any password protection.

_TL;DR Is it possible to have docker-host access applications bound to `127.0.0.1`?_

**docker-compose.yml**

```
version: '3'
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - docker-host
    ports:
      - 7004:7004
```

**nginx.conf**
```
events { worker_connections 1024; }

http {
  server {
    listen 7004;

    server_name localhost;

    location / {
      proxy_pass http://docker-host:7005;
      auth_basic "Basic auth";
      auth_basic_user_file /etc/nginx/.htpasswd;
    }
  }
}
```

**Comment by qoomon** [comment]
try to use '--host localhost' instead of '--host 127.0.0.1' as described in this tensorflow [issue](https://github.com/tensorflow/tensorboard/issues/89)

**Comment by qoomon** [comment]
So basically it should work like you expecting docker-host to work. I just tested it with running a simple http-server on 127.0.0.1 and it works out of the box

**Comment by Mastergalen** [comment]
Thanks for testing this.

Perhaps it's an issue with how Tensorboard implements their binding.

I decided to just shove Tensorboard inside a Docker container as well instead and I can just use `http://tensorboard:6006` inside the `nginx` container.

**docker-compose.yml**

```yml
version: '3'
services:
  tensorboard:
    image: tensorflow/tensorflow
    entrypoint:
      - tensorboard
      - --logdir
      - /tf_logs
    volumes:
      - "${LOG_DIR}:/tf_logs"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: always
    volumes:
      - ./nginx.template:/etc/nginx/nginx.template
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - tensorboard
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
```
