### ISSUE TITLE
Ping (icmp) work but not tcp

### ISSUE THREAD

**Issue by Hubbitus** [qoomon/docker-host#14]
$ cat docker-compose.yml
```yaml
version: '2'

networks:
  some-net:
    driver: bridge

services:
  # On host do: curl http://localhost:8888 and you get result
  nginx-for-test:
    image: nginx
    ports:
      - "8888:80"

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - some-net
  test:
    image: appropriate/curl
    command: ["curl" , "http://dockerhost:8888"]
    networks:
      - some-net
```

`docker-compose up` output:
```
Attaching to dockerhost_dockerhost_1, dockerhost_nginx-for-test_1, dockerhost_test_1
dockerhost_1      | Docker Host: 172.22.0.1 (default gateway)
test_1            |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
test_1            |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to dockerhost port 8888: Host is unreachable
dockerhost_test_1 exited with code 7
```

**Comment by qoomon** [comment]
hi, your problem occurs because when the curl command is executed the dockerhost container is not ready. icmp is working because you got an pong from the dockerhost container not from the real docker host.
Possible solutions:
* wait some seconds before you execute the curl command
* start dockerhost container `docker-compose up -d dockerhost` first wait some seconds ramp up the rest `docker-compose up -d`

**Comment by Hubbitus** [comment]
No, it does not work at all:
```
$ docker-compose up -d dockerhost
Starting dockerhost_dockerhost_1 ... done
[pasha@2 dockerhost]$ sleep 30
[pasha@2 dockerhost]$ docker-compose up -d
dockerhost_dockerhost_1 is up-to-date
Starting dockerhost_nginx-for-test_1 ... done
Starting dockerhost_test_1           ... done
[pasha@2 dockerhost]$ d logs dockerhost_test_1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: dockerhost
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to dockerhost port 8888: Host is unreachable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to dockerhost port 8888: Host is unreachable
```

**Comment by qoomon** [comment]
Strange which host system do you use? I'm working on a macOS system.

**Comment by qoomon** [comment]
please try 
```bash
docker-compose up -d nginx-for-test dockerhost
sleep 10
docker-compose up test
```

**Comment by qoomon** [comment]
can you provide some more details?
docker engine version docker compose version and os version

**Comment by qoomon** [comment]
actually I have no clue why it does not work for you :/

**Comment by qoomon** [comment]
I made so research and it seems to be a fedora related problem.
when Execute the `iptable` command within a container on a fedora host I got the error `iptables: No chain/target/match by that name.`
This seems to be caused by a missing/not loaded kernel module
To fix it you have to load them on fedora host
`sudo modprobe xt_multiport`
`sudo modprobe xt_nat`

**Comment by Hubbitus** [comment]
Could you please dump your `iptables` rules?

**Comment by Hubbitus** [comment]
What also may be interesting, I also do some experiments. If I run `nginx` in `host network mode`, it works!

```yaml
version: '2'

networks:
  some-net:
    driver: bridge

services:
  # On host do: curl http://localhost:8888 and you get result
  nginx-for-test:
    image: nginx
    ports:
      - "8888:80"
    network_mode: "host"

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - some-net
  test:
    image: appropriate/curl
    entrypoint: sh
    command: -c 'sleep 10 && curl http://dockerhost:80'
    networks:
      - some-net
```

```bash
$ docker-compose up
Starting dockerhost_nginx-for-test_1 ... done
Starting dockerhost_dockerhost_1     ... done
Recreating dockerhost_test_1         ... done
Attaching to dockerhost_nginx-for-test_1, dockerhost_dockerhost_1, dockerhost_test_1
dockerhost_1      | Docker Host: 192.168.0.1 (default gateway)
test_1            |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
test_1            |                                  Dload  Upload   Total   Spent    Left  Speed
nginx-for-test_1  | 192.168.0.2 - - [13/Dec/2018:16:45:45 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.59.0" "-"
100   612  100   612    0     0  76500      0 --:--:-- --:--:-- --:--:-- 76500
test_1            | <!DOCTYPE html>
test_1            | <html>
test_1            | <head>
test_1            | <title>Welcome to nginx!</title>
test_1            | <style>
test_1            |     body {
test_1            |         width: 35em;
test_1            |         margin: 0 auto;
test_1            |         font-family: Tahoma, Verdana, Arial, sans-serif;
test_1            |     }
test_1            | </style>
test_1            | </head>
test_1            | <body>
test_1            | <h1>Welcome to nginx!</h1>
test_1            | <p>If you see this page, the nginx web server is successfully installed and
test_1            | working. Further configuration is required.</p>
test_1            | 
test_1            | <p>For online documentation and support please refer to
test_1            | <a href="http://nginx.org/">nginx.org</a>.<br/>
test_1            | Commercial support is available at
test_1            | <a href="http://nginx.com/">nginx.com</a>.</p>
test_1            | 
test_1            | <p><em>Thank you for using nginx.</em></p>
test_1            | </body>
test_1            | </html>
dockerhost_test_1 exited with code 0
```

In that case I can't map ports and change it for test on 80 too.
But still does not work for ports exposed by other containers from different networks.

**Comment by qoomon** [comment]
I tested it with this image https://getfedora.org/en_GB/atomic/download/download-cloud-splash?file=https://download.fedoraproject.org/pub/alt/atomic/stable/Fedora-29-updates-20181210.0/AtomicHost/x86_64/images/Fedora-AtomicHost-Vagrant-29-20181210.0.x86_64.vagrant-virtualbox.box

**Comment by qoomon** [comment]
`sudo iptables --list-rules`
output:
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
```

**Comment by qoomon** [comment]
It seems to be a fedora specific issue, I not used to fedora so I need help for solving this

**Comment by Hubbitus** [comment]
Does it works on Fedora in same way for you?

**Comment by qoomon** [comment]
Yes it does, however I used the atomic host version of fedora, maybe that's why.

**Comment by Hubbitus** [comment]
Does it works on Fedora in same way for you?

**Comment by qoomon** [comment]
Closed due to inactivity.

**Comment by Hubbitus** [comment]
Why??

**Comment by mojeto** [comment]
I experience the same issue on linux Mint (Ubuntu) host.
I did some trial and error and I think the problem is somewhere with docker on linux.
I tried the absolute minimum by running 
```
# executed inside docker container shell
telnet $(ip -4 route show default | cut -d' ' -f3) 22
```
I'm able to get connection to my host ssh service running on port 22.

now, if I run nginx container on host port 8888. I can access the port 8888 from host machine without problem.
But I **can't** access the same port 8888 from another container using the same technique as before.
```
# executed inside docker container shell
telnet $(ip -4 route show default | cut -d' ' -f3) 8888
```
doesn't work on linux host.

I've also tested it on macOS Mojave and both scenarios above work. (using `docker.host.internal` )

In last few weeks I found that docker networking on Docker for Mac app and on docker for linux don't work the same and they both have quite a few different unexpected limitations like this one.

**Comment by qoomon** [comment]
@mojeto could you try following command to determine ip address from within the container `netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}'`

**Comment by qoomon** [comment]
@mojeto  could you provide the output of  `docker ps` for your nginx container

**Comment by mojeto** [comment]
docker-compose file I used for the test
```
version: '3.7'

services:
  # On host do: curl http://localhost:8080 and you get result
  nginx-for-test:
    image: nginx
    ports:
      - "8888:80"

  test:
    image: nicolaka/netshoot
```
`docker ps`


```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
2a38470c1b3c        nginx               "nginx -g 'daemon of…"   5 minutes ago       Up 5 minutes        0.0.0.0:8888->80/tcp   test2_nginx-for-test_1_806f155b6b9b
```
