### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by lrkwz** [qoomon/docker-host#25]
I cannot make the gateway work properly.
I've read #21 and bound my app to the host ip `172.20.0.1` (resulting from `docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'`).

Relevant part of docker-compose.yml is:

```yml
version: '3'
services:
    my-api-gateway:
        image: qoomon/docker-host
        cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
        # mem_limit: 4M
        restart: on-failure
    web:
        image: my-webapp-ui
        ports:
        - "80:80"
```

Then I start the java api `mvn spring-boot:run` which listens on `172.20.0.1` port `8080`.

From the host shell:
```bash
$ curl http://172.20.0.1:8080/management/health
{
  "status" : "UP"
}
```
From the goomon/docker-host container:

```bash
$ docker-compose exec my-api-gateway sh
# curl http://172.20.0.1:8080/management/health
{
  "status" : "UP"
} 
```

From the linked container:
```bash
$  docker-compose exec web sh
# curl http://my-api-gateway:8080/management/health
curl: (7) Failed to connect to my-api-gateway port 8080: Operation timed out
```

What's wrong in my config?
