### ISSUE TITLE
How to use with existing docker-compose

### ISSUE THREAD

**Issue by MacGyver27** [qoomon/docker-host#26]
Hi, sorry for dumb question but I dont not follow how this should be used.. If we should add `dockerhost` per docker-compose.yml or it should run as standalone container somewhere on the host..

I have a docker-compose file for guacamole and want to be able to access host from that container (it is a web ui to VNC machine, and want to VNC the host). What are the steps please? Imagine I freshly installed docker and docker compose and pulled docker-compose.yml file:
```yml
version: '2.0'

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacamole.508.guacd
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  # postgres
  postgres:
    container_name: guacamole.508.postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole
      POSTGRES_PASSWORD: ***********************
      POSTGRES_USER: guacamole
    image: postgres
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    container_name: guacamole.508
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ***********************
      POSTGRES_USER: guacamole
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnetwork_compose:
    ports:
    - 50880:8080/tcp
    restart: always
```

Any hints will be appreciated, thanks!
