### ISSUE TITLE
Cant find dockerhost

### ISSUE THREAD

**Issue by jpkontreras** [qoomon/docker-host#29]
Hello 
I want to connect to a postgres DB on my local machine through a container
im using docker compose v3 

docker-compose.yml
```
version: '3.5'

services:
  dockerhost:
    build:
      context: ../
      dockerfile: ./docker/files/host.dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
    networks:
      - backend
  backend_app:
    container_name: agenda_api_app_dev
    build:
      context: ../
      dockerfile: ./docker/files/app.dockerfile
    volumes:
      - ../:/var/www/
    networks:
      - backend
    depends_on:
      - dockerhost
  backend_server:
    container_name: agenda_api_server_dev
    build:
      context: ..
      dockerfile: ./docker/files/server.dockerfile
    volumes:
      - ../public:/var/www/public
      - ../storage/logs/:/var/log/nginx
    ports:
      - ${APP_PORT}:80
    depends_on:
      - backend_app
    networks:
      - backend
networks:
  backend:
    driver: bridge
```
host.dockerfile
```
FROM qoomon/docker-host:latest
```

When executed shows dockerhost as unknown . What it could be ?
<img width="1028" alt="Captura de Pantalla 2020-03-11 a la(s) 14 48 30" src="https://user-images.githubusercontent.com/7862089/76447413-685f8480-63a7-11ea-9bd8-e49baddb8284.png">

Im active if you want more info
