### ISSUE TITLE
setup correctly connection from container to Docker API 

### ISSUE THREAD

**Issue by pisarevaa** [qoomon/docker-host#38]
### Could you please explain how to setup correctly connection from container to Docker API or host port 2375 in Linux machine.
1. I have opened port 2375 to connect to Docker API in /lib/systemd/system/docker.service:
`ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://127.0.0.1:2375`
2. My docker-compose.yml is:
```
version: '3.7'
services:
  web:
    image: some_image
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app/
    ports:
      - 80:80
    depends_on:
      - docker-host
    networks:
      - app-network
    env_file:
      - ./.env
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
```
3. After that I connect to container via `sudo docker exec -it web_1 bash`
4. Run command inside container `curl -X GET host.docker.internal:2375/containers/json` and get an error `curl: (6) Could not resolve host: host.docker.internal`

Where am I wrong?

**Comment by pisarevaa** [comment]
I ended up with the following steps:
1. Added unix socket to Docker API in /lib/systemd/system/docker.service:
`ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock`
2. Add volume /var/run/docker.sock to docker-compose.yml is:
```
version: '3.7'
services:
  web:
    image: some_image
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    depends_on:
      - docker-host
    networks:
      - app-network
    env_file:
      - ./.env
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
```
3. Run command succesfully` curl -XGET --unix-socket /var/run/docker.sock localhost:2375/containers/json`
