### ISSUE TITLE
Can't reach database server at `dockerhost`

### ISSUE THREAD

**Issue by heriisei** [qoomon/docker-host#40]
I followed https://medium.com/@sam_ngu/connecting-to-docker-host-mysql-from-docker-container-linux-ubuntu-766e526542fd to connect to my host MySQL database.

Inside the other container, I could ping the dockerhost container.

My project is using Prisma as a DB access layer, and pointed to the DB via URL like this:
`mysql://user:password@dockerhost:3306/schema`.

But when I tried to access the DB. I ended up getting this error:
`"Can't reach database server at 'dockerhost':'3306'. Please make sure your database server is running at 'dockerhost':'3306'"`

All the configurations are set up as mentioned in the above medium article, like the firewall, DB user, etc.
```
dockerhost:
  image: qoomon/docker-host
  cap_add:
    - NET_ADMIN
    - NET_RAW
  restart: on-failure
  networks:
    - internal
```

The dockerhost container log is also showing no error.
```
Docker Host: 172.22.0.1 (default gateway)
Forwarding ports: 0:65535
```

I would be so happy to get any solution :smiley: from you guys.
Thank you
