### ISSUE TITLE
Latest Update Causes Issues on Docker For Mac

### ISSUE THREAD

**Issue by eligundry** [qoomon/docker-host#42]
Hello, we are using Docker Host on our Macs with Docker Compose. One of the developers on my team did a `docker-compose pull` this afternoon and then `docker-compose up` and docker-host started exiting immediately with the following error:

```
[ERROR] docker-host container needs Linux capabilities NET_ADMIN and NET_RAW
  e.g 'docker run --cap-add=NET_ADMIN --cap-add=NET_RAW ...'
```

I then did a `docker-compose pull` and `docker-compose up` on my machine and got the same error. I then looked at the previous Docker tags and pinned my version in Docker Compose to 2.5.4. `docker-compose up` and no error.

Below is a before an after of the service for docker-host in our Docker Composes.

```yaml
  # This exits immediately 
  docker-host:
    container_name: products-docker-host
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
```

```yaml
  # This works
  docker-host:
    container_name: products-docker-host
    image: qoomon/docker-host:2.5.4
    cap_add:
      - NET_ADMIN
      - NET_RAW
```

What is weird is that your newest release appears to be just a [documentation change](https://github.com/qoomon/docker-host/commit/ea7df4a08710cc4349058c222a5eb6f6de2e6121) (nifty little star graph!) so maybe something changed in the base image?
