### ISSUE TITLE
docker-host fails to start sometimes

### ISSUE THREAD

**Issue by madhavajay** [qoomon/docker-host#44]
For some reason, only on the cloud Ubuntu 20.04 VMs that I create myself, sometimes `docker-host` does not start.

Also this issue never happens on GitHub CI or MacOS.

I have it set to always restart in the docker-compose file:
```
docker-host:
  depends_on:
    - proxy
    - pgadmin
    - db
    - flower
    - queue
    - backend
    - backend_stream
    - celeryworker
    - frontend
    - tailscale
    - headscale
  image: qoomon/docker-host
  cap_add:
    - net_admin
    - net_raw
  mem_limit: 8M
  restart: always
```

I can sometimes manually start it after the fact but if this is running CI it will cause failures. The only thing I can think of is the container is trying to start and then backing off and finally stopping. Unfortunately there is nothing in the logs to show any reason why it failed to start.

Do you have any idea why this would happen or if there is a way to make sure it will definitely start no matter what?

Perhaps I need to give it a little `sleep` before hand?

<img width="646" alt="Screen Shot 2021-10-26 at 9 51 12 am" src="https://user-images.githubusercontent.com/2882739/138796752-0d929d4f-02ff-4881-8d33-6ebc856ce4ce.png">
