### ISSUE TITLE
docker compose v3.3

### ISSUE THREAD

**Issue by anestere** [qoomon/docker-host#5]
Failed to run docker-compose 3.3

```yaml
version: "3.3"

services:

  dockerhost:
    image: qoomon/docker-host
    cap_drop:
    - NET_ADMIN
    - NET_RAW
    deploy:
      resources:
        limits:
          memory: 4M
      restart_policy:
        condition: on-failure
    environment:
      - PORTS=0:1024,9000
```

**dockerhost_1  | multiport: Could not determine whether revision 1 is supported, assuming it is.
dockerhost_1  | Docker Host Gateway: 193.164.64.2
dockerhost_1  | iptables v1.6.2: can't initialize iptables table `nat': Permission denied (you must be root)
dockerhost_1  | Perhaps iptables or your kernel needs to be upgraded.**
