### ISSUE TITLE
Depreciated?

### ISSUE THREAD

**Issue by bOmBeLq** [qoomon/docker-host#60]
Hello, I've been using your image for some time. I really appreciate what your hard work. It was big help for me. 
But lately I've discovered you can use
```
services:
  name:
    [...]
    extra_hosts:
      - host.docker.internal:host-gateway
```
Is there use of docker-host if we can do this?
I guess docker-host gives ability to forward only specific ports but maybe it would be good to add this extra_hosts alternative to readme, what do you think?
